#include <SDL2/SDL.h>
#include <SDL2/SDL_events.h>
#include <SDL2/SDL_keycode.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_stdinc.h>
#include <SDL2/SDL_video.h>
#include <oak/std/std_oak_header.h>
#include <string.h>

struct sdl_Window {
  SDL_Window *window;
  SDL_Renderer *renderer;
};
static_assert(sizeof(struct sdl_Window) == 2 * sizeof(void *));

struct sdl_Color {
  u8 r, g, b, a;
};

struct sdl_Coord {
  int x, y;
};

struct sdl_Rect {
  int x, y, w, h;
};

struct sdl_KeyEventData {
  int keycode;
};

struct sdl_MouseMoveEventData {
  int x, y;
};

struct sdl_MouseButtonEventData {
  int x, y;
  u8 code;
};

struct sdl_MiscData {
  u32 code;
};

struct Unit {
  u8 _;
};

struct sdl_Event {
  enum {
    sdl_Event_OPT_none,
    sdl_Event_OPT_key_down_event,
    sdl_Event_OPT_key_up_event,
    sdl_Event_OPT_mouse_move_event,
    sdl_Event_OPT_mouse_button_down_event,
    sdl_Event_OPT_mouse_button_up_event,
    sdl_Event_OPT_misc_event,
    sdl_Event_OPT_quit_event,
  } __info;
  union {
    struct Unit none;
    struct sdl_KeyEventData key_down_event;
    struct sdl_KeyEventData key_up_event;
    struct sdl_MouseMoveEventData mouse_move_event;
    struct sdl_MouseButtonEventData mouse_button_down_event;
    struct sdl_MouseButtonEventData mouse_button_up_event;
    struct sdl_MiscData misc_event;
    struct Unit quit_event;
  } __data;
};

// Auto-generated by Oak
void wrap_key_down_event_FN_PTR_sdl_Event_JOIN_sdl_KeyEventData_MAPS_void(
    struct sdl_Event *, struct sdl_KeyEventData);
void wrap_key_up_event_FN_PTR_sdl_Event_JOIN_sdl_KeyEventData_MAPS_void(
    struct sdl_Event *, struct sdl_KeyEventData);
void wrap_misc_event_FN_PTR_sdl_Event_JOIN_sdl_MiscData_MAPS_void(
    struct sdl_Event *, struct sdl_MiscData);
void wrap_mouse_button_down_event_FN_PTR_sdl_Event_JOIN_sdl_MouseButtonEventData_MAPS_void(
    struct sdl_Event *, struct sdl_MouseButtonEventData);
void wrap_mouse_button_up_event_FN_PTR_sdl_Event_JOIN_sdl_MouseButtonEventData_MAPS_void(
    struct sdl_Event *, struct sdl_MouseButtonEventData);
void wrap_mouse_move_event_FN_PTR_sdl_Event_JOIN_sdl_MouseMoveEventData_MAPS_void(
    struct sdl_Event *, struct sdl_MouseMoveEventData);
void wrap_none_FN_PTR_sdl_Event_JOIN_Unit_MAPS_void(
    struct sdl_Event *, struct Unit);
void wrap_quit_event_FN_PTR_sdl_Event_JOIN_Unit_MAPS_void(
    struct sdl_Event *, struct Unit);

// sdl_poll_event() -> sdl_Event
struct sdl_Event sdl_poll_event_FN_MAPS_sdl_Event() {
  struct sdl_Event out;
  struct Unit unit;
  wrap_none_FN_PTR_sdl_Event_JOIN_Unit_MAPS_void(&out, unit);

  SDL_Event event;
  if (SDL_PollEvent(&event) == 1) {
    switch (event.type) {
    case SDL_KEYDOWN: {
      struct sdl_KeyEventData data;
      data.keycode = event.key.keysym.sym;
      wrap_key_down_event_FN_PTR_sdl_Event_JOIN_sdl_KeyEventData_MAPS_void(
          &out, data);
    } break;
    case SDL_KEYUP: {
      struct sdl_KeyEventData data;
      data.keycode = event.key.keysym.sym;
      wrap_key_up_event_FN_PTR_sdl_Event_JOIN_sdl_KeyEventData_MAPS_void(
          &out, data);
    } break;
    case SDL_MOUSEMOTION: {
      struct sdl_MouseMoveEventData data;
      data.x = event.button.x;
      data.y = event.button.y;
      wrap_mouse_move_event_FN_PTR_sdl_Event_JOIN_sdl_MouseMoveEventData_MAPS_void(
          &out, data);
    } break;
    case SDL_MOUSEBUTTONDOWN: {
      struct sdl_MouseButtonEventData data;
      data.code = event.button.button;
      data.x = event.button.x;
      data.y = event.button.y;
      wrap_mouse_button_down_event_FN_PTR_sdl_Event_JOIN_sdl_MouseButtonEventData_MAPS_void(
          &out, data);
    } break;
    case SDL_MOUSEBUTTONUP: {
      struct sdl_MouseButtonEventData data;
      data.code = event.button.button;
      data.x = event.button.x;
      data.y = event.button.y;
      wrap_mouse_button_up_event_FN_PTR_sdl_Event_JOIN_sdl_MouseButtonEventData_MAPS_void(
          &out, data);
    } break;

    case SDL_QUIT:
      wrap_quit_event_FN_PTR_sdl_Event_JOIN_Unit_MAPS_void(
          &out, unit);
      break;

    default: {
      struct sdl_MiscData data;
      data.code = event.type;
      wrap_misc_event_FN_PTR_sdl_Event_JOIN_sdl_MiscData_MAPS_void(
          &out, data);
    } break;
    }
  }

  return out;
}

// New(self: ^sdl_Window) -> void
void New_FN_PTR_sdl_Window_MAPS_void(struct sdl_Window *self) {
  SDL_CreateWindowAndRenderer(128, 128, 0, &self->window,
                              &self->renderer);
}

// Del(self: ^sdl_Window) -> void
void Del_FN_PTR_sdl_Window_MAPS_void(struct sdl_Window *self) {
  SDL_DestroyWindow(self->window);
  SDL_DestroyRenderer(self->renderer);
}

// Copy(self: ^sdl_Window, w: u64, h: u64) -> sdl_Window
void Copy_FN_PTR_sdl_Window_JOIN_u64_JOIN_u64_MAPS_void(
    struct sdl_Window *self, u64 w, u64 h) {
  SDL_SetWindowSize(self->window, w, h);
}

// sdl_enable_window_fullscreen(self: ^sdl_Window) -> void
void sdl_enable_window_fullscreen_FN_PTR_sdl_Window_MAPS_void(
    struct sdl_Window *self) {
  SDL_SetWindowFullscreen(self->window,
                          SDL_WINDOW_FULLSCREEN_DESKTOP);
}

// sdl_disable_window_fullscreen(self: ^sdl_Window) -> void
void sdl_disable_window_fullscreen_FN_PTR_sdl_Window_MAPS_void(
    struct sdl_Window *self) {
  SDL_SetWindowFullscreen(self->window, 0);
}

// sdl_save(self: ^sdl_Window, filepath: []i8) -> void
void sdl_save_FN_PTR_sdl_Window_JOIN_ARR_i8_MAPS_void(
    struct sdl_Window *self, i8 *filepath) {
  puts("sdl_save_FN_PTR_sdl_Window_JOIN_ARR_i8_MAPS_void is "
       "unimplemented!");
  exit(128);
}

// sdl_sin(x: f64) -> f64
f64 sdl_sin_FN_f64_MAPS_f64(f64 x) {
  return SDL_sin(x);
}

// sdl_cos(x: f64) -> f64
f64 sdl_cos_FN_f64_MAPS_f64(f64 x) {
  return SDL_cos(x);
}

// sdl_tan(x: f64) -> f64
f64 sdl_tan_FN_f64_MAPS_f64(f64 x) {
  return SDL_tan(x);
}

// sdl_init() -> void
void sdl_init_FN_MAPS_void() {
  SDL_Init(SDL_INIT_EVERYTHING);
}

// sdl_quit() -> void
void sdl_quit_FN_MAPS_void() {
  SDL_Quit();
}

// sdl_delay(ms: i32) -> void
void sdl_delay_FN_i32_MAPS_void(i32 ms) {
  SDL_Delay(ms);
}

// sdl_get_ticks() -> u64
u64 sdl_get_ticks_FN_MAPS_u64() {
  return SDL_GetTicks64();
}

// show(window: ^sdl_Window) -> void
void show_FN_PTR_sdl_Window_MAPS_void(
    struct sdl_Window *window) {
  SDL_RenderPresent(window->renderer);
}

// fill(window: ^sdl_Window, color: sdl_Color) -> void
void fill_FN_PTR_sdl_Window_JOIN_sdl_Color_MAPS_void(
    struct sdl_Window *window, struct sdl_Color color) {
  SDL_SetRenderDrawColor(window->renderer, color.r, color.g,
                         color.b, color.a);
  SDL_RenderFillRect(window->renderer, NULL);
}

// draw_dot(window: ^sdl_Window, point: sdl_Coord, color:
// sdl_Color) -> void
void draw_dot_FN_PTR_sdl_Window_JOIN_sdl_Coord_JOIN_sdl_Color_MAPS_void(
    struct sdl_Window *window, struct sdl_Coord point,
    struct sdl_Color color) {
  SDL_SetRenderDrawColor(window->renderer, color.r, color.g,
                         color.b, color.a);
  SDL_RenderDrawPoint(window->renderer, point.x, point.y);
}

// draw_line(window: ^sdl_Window, point_a: sdl_Coord, point_b:
// sdl_Coord, color: sdl_Color) -> void
void draw_line_FN_PTR_sdl_Window_JOIN_sdl_Coord_JOIN_sdl_Coord_JOIN_sdl_Color_MAPS_void(
    struct sdl_Window *window, struct sdl_Coord point_a,
    struct sdl_Coord point_b, struct sdl_Color color) {
  SDL_SetRenderDrawColor(window->renderer, color.r, color.g,
                         color.b, color.a);
  SDL_RenderDrawLine(window->renderer, point_a.x, point_a.y,
                     point_b.x, point_b.y);
}

// draw_rect(window: ^sdl_Window, rect: sdl_Rect, color:
// sdl_Color) -> void
void draw_rect_FN_PTR_sdl_Window_JOIN_sdl_Rect_JOIN_sdl_Color_MAPS_void(
    struct sdl_Window *window, struct sdl_Rect rect,
    struct sdl_Color color) {
  SDL_SetRenderDrawColor(window->renderer, color.r, color.g,
                         color.b, color.a);

  SDL_Rect sdl_rect;
  sdl_rect.x = rect.x;
  sdl_rect.y = rect.y;
  sdl_rect.w = rect.w;
  sdl_rect.h = rect.h;
  SDL_RenderDrawRect(window->renderer, &sdl_rect);
}

// fill_rect(window: ^sdl_Window, rect: sdl_Rect, color:
// sdl_Color) -> void
void fill_rect_FN_PTR_sdl_Window_JOIN_sdl_Rect_JOIN_sdl_Color_MAPS_void(
    struct sdl_Window *window, struct sdl_Rect rect,
    struct sdl_Color color) {
  SDL_SetRenderDrawColor(window->renderer, color.r, color.g,
                         color.b, color.a);

  SDL_Rect sdl_rect;
  sdl_rect.x = rect.x;
  sdl_rect.y = rect.y;
  sdl_rect.w = rect.w;
  sdl_rect.h = rect.h;
  SDL_RenderFillRect(window->renderer, &sdl_rect);
}

// size(self: ^sdl_Window) -> sdl_Rect
struct sdl_Rect
size_FN_PTR_sdl_Window_MAPS_sdl_Rect(struct sdl_Window *self) {
  int w = 0, h = 0;
  SDL_GetRendererOutputSize(self->renderer, &w, &h);

  struct sdl_Rect out;
  out.w = w;
  out.h = h;
  out.x = out.y = 0;
  return out;
}

#define __case(a)                                              \
  case a:                                                      \
    strncpy((char *)buffer, #a, n);                            \
    break

// sdl_to_str(keycode: i64, buffer: []i8, n: u64) -> void
void sdl_to_str_FN_i64_JOIN_ARR_i8_JOIN_u64_MAPS_void(
    i64 keycode, i8 *buffer, u64 n) {
  if (n <= 0) {
    return;
  }

  if (keycode > 0 && keycode < 255 && isprint(keycode)) {
    buffer[0] = keycode;
    if (n > 1) {
      buffer[1] = '\0';
    }
    return;
  }

  switch (keycode) {
    __case(SDLK_CAPSLOCK);
    __case(SDLK_F1);
    __case(SDLK_F2);
    __case(SDLK_F3);
    __case(SDLK_F4);
    __case(SDLK_F5);
    __case(SDLK_F6);
    __case(SDLK_F7);
    __case(SDLK_F8);
    __case(SDLK_F9);
    __case(SDLK_F10);
    __case(SDLK_F11);
    __case(SDLK_F12);
    __case(SDLK_PRINTSCREEN);
    __case(SDLK_SCROLLLOCK);
    __case(SDLK_PAUSE);
    __case(SDLK_INSERT);
    __case(SDLK_HOME);
    __case(SDLK_PAGEUP);
    __case(SDLK_END);
    __case(SDLK_SOFTLEFT);
    __case(SDLK_SOFTRIGHT);
    __case(SDLK_ESCAPE);
    __case(SDLK_PAGEDOWN);
    __case(SDLK_RIGHT);
    __case(SDLK_LEFT);
    __case(SDLK_DOWN);
    __case(SDLK_UP);
    __case(SDLK_NUMLOCKCLEAR);
    __case(SDLK_KP_DIVIDE);
    __case(SDLK_KP_MULTIPLY);
    __case(SDLK_KP_MINUS);
    __case(SDLK_KP_PLUS);
    __case(SDLK_KP_ENTER);
    __case(SDLK_KP_1);
    __case(SDLK_KP_2);
    __case(SDLK_KP_3);
    __case(SDLK_KP_4);
    __case(SDLK_KP_5);
    __case(SDLK_KP_6);
    __case(SDLK_KP_7);
    __case(SDLK_KP_8);
    __case(SDLK_KP_9);
    __case(SDLK_KP_0);
    __case(SDLK_KP_PERIOD);
    __case(SDLK_APPLICATION);
    __case(SDLK_POWER);
    __case(SDLK_KP_EQUALS);
    __case(SDLK_F13);
    __case(SDLK_F14);
    __case(SDLK_F15);
    __case(SDLK_F16);
    __case(SDLK_F17);
    __case(SDLK_F18);
    __case(SDLK_F19);
    __case(SDLK_F20);
    __case(SDLK_F21);
    __case(SDLK_F22);
    __case(SDLK_F23);
    __case(SDLK_F24);
    __case(SDLK_EXECUTE);
    __case(SDLK_HELP);
    __case(SDLK_MENU);
    __case(SDLK_SELECT);
    __case(SDLK_STOP);
    __case(SDLK_AGAIN);
    __case(SDLK_UNDO);
    __case(SDLK_CUT);
    __case(SDLK_COPY);
    __case(SDLK_PASTE);
    __case(SDLK_FIND);
    __case(SDLK_MUTE);
    __case(SDLK_VOLUMEUP);
    __case(SDLK_VOLUMEDOWN);
    __case(SDLK_KP_COMMA);
    __case(SDLK_KP_EQUALSAS400);
    __case(SDLK_ALTERASE);
    __case(SDLK_SYSREQ);
    __case(SDLK_CANCEL);
    __case(SDLK_CLEAR);
    __case(SDLK_PRIOR);
    __case(SDLK_RETURN2);
    __case(SDLK_SEPARATOR);
    __case(SDLK_OUT);
    __case(SDLK_OPER);
    __case(SDLK_CLEARAGAIN);
    __case(SDLK_CRSEL);
    __case(SDLK_EXSEL);
    __case(SDLK_KP_00);
    __case(SDLK_KP_000);
    __case(SDLK_THOUSANDSSEPARATOR);
    __case(SDLK_DECIMALSEPARATOR);
    __case(SDLK_CURRENCYUNIT);
    __case(SDLK_CURRENCYSUBUNIT);
    __case(SDLK_KP_LEFTPAREN);
    __case(SDLK_KP_RIGHTPAREN);
    __case(SDLK_KP_LEFTBRACE);
    __case(SDLK_KP_RIGHTBRACE);
    __case(SDLK_KP_TAB);
    __case(SDLK_KP_BACKSPACE);
    __case(SDLK_KP_A);
    __case(SDLK_KP_B);
    __case(SDLK_KP_C);
    __case(SDLK_KP_D);
    __case(SDLK_KP_E);
    __case(SDLK_KP_F);
    __case(SDLK_KP_XOR);
    __case(SDLK_KP_POWER);
    __case(SDLK_KP_PERCENT);
    __case(SDLK_KP_LESS);
    __case(SDLK_KP_GREATER);
    __case(SDLK_KP_AMPERSAND);
    __case(SDLK_KP_DBLAMPERSAND);
    __case(SDLK_KP_VERTICALBAR);
    __case(SDLK_KP_DBLVERTICALBAR);
    __case(SDLK_KP_COLON);
    __case(SDLK_KP_HASH);
    __case(SDLK_KP_SPACE);
    __case(SDLK_KP_AT);
    __case(SDLK_KP_EXCLAM);
    __case(SDLK_KP_MEMSTORE);
    __case(SDLK_KP_MEMRECALL);
    __case(SDLK_KP_MEMCLEAR);
    __case(SDLK_KP_MEMADD);
    __case(SDLK_KP_MEMSUBTRACT);
    __case(SDLK_KP_MEMMULTIPLY);
    __case(SDLK_KP_MEMDIVIDE);
    __case(SDLK_KP_PLUSMINUS);
    __case(SDLK_KP_CLEAR);
    __case(SDLK_KP_CLEARENTRY);
    __case(SDLK_KP_BINARY);
    __case(SDLK_KP_OCTAL);
    __case(SDLK_KP_DECIMAL);
    __case(SDLK_KP_HEXADECIMAL);
    __case(SDLK_LCTRL);
    __case(SDLK_LSHIFT);
    __case(SDLK_LALT);
    __case(SDLK_LGUI);
    __case(SDLK_RCTRL);
    __case(SDLK_RSHIFT);
    __case(SDLK_RALT);
    __case(SDLK_RGUI);
    __case(SDLK_MODE);
    __case(SDLK_AUDIONEXT);
    __case(SDLK_AUDIOPREV);
    __case(SDLK_AUDIOSTOP);
    __case(SDLK_AUDIOPLAY);
    __case(SDLK_AUDIOMUTE);
    __case(SDLK_MEDIASELECT);
    __case(SDLK_WWW);
    __case(SDLK_MAIL);
    __case(SDLK_CALCULATOR);
    __case(SDLK_COMPUTER);
    __case(SDLK_AC_SEARCH);
    __case(SDLK_AC_HOME);
    __case(SDLK_AC_BACK);
    __case(SDLK_AC_FORWARD);
    __case(SDLK_AC_STOP);
    __case(SDLK_AC_REFRESH);
    __case(SDLK_AC_BOOKMARKS);
    __case(SDLK_BRIGHTNESSDOWN);
    __case(SDLK_BRIGHTNESSUP);
    __case(SDLK_DISPLAYSWITCH);
    __case(SDLK_KBDILLUMTOGGLE);
    __case(SDLK_KBDILLUMDOWN);
    __case(SDLK_KBDILLUMUP);
    __case(SDLK_EJECT);
    __case(SDLK_SLEEP);
    __case(SDLK_APP1);
    __case(SDLK_APP2);
    __case(SDLK_AUDIOREWIND);
    __case(SDLK_AUDIOFASTFORWARD);
    __case(SDLK_CALL);
    __case(SDLK_ENDCALL);
  default:
    buffer[0] = '\0';
    break;
  }
}

#undef __case
