/**
 * @file
 */

#include "parser.hpp"
#include "ast_node.hpp"
#include "compiler.hpp"
#include "lexer.hpp"
#include "parse_helpers.hpp"
#include "settings.hpp"
#include "symbols.hpp"
#include "type.hpp"
#include <cassert>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <memory>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <variant>

/// Internal oak macros
const static std::set<std::string> reserved_macro_names = {
    "alias!",
    "c!",
    "compile_time_error!",
    "compile_time_print!",
    "compile_time_system!",
    "compile_time_warning!",
    "erase!",
    "flag!",
    "include!",
    "link!",
    "namespace_use!",
    "pragma!",
    "rule_bundle!",
    "rule_new!",
    "rule_remove!",
    "rule_use!",
    "size!",
    "str!",
    "type!",
    "unstr!",
    "LINE!",
    "COL!",
    "FILE!",
    "oak_VERSION!",
    "SYSTEM!",
};

void Parser::parse_global(TokenStream &_pos) {
  debug_print_pos(__FUNCTION__, _pos);

  while (!_pos.done()) {
    try {
      parse_statement(_pos);
    } catch (std::runtime_error &e) {
      throw std::runtime_error(
          "At " + _pos.cur().file.string() + ":" +
          std::to_string(_pos.cur().line) + "." +
          std::to_string(_pos.cur().col) + "\n" + e.what());
    }
    // catch (...) {
    //   throw std::runtime_error(
    //       "At " + _pos.cur().file.string() + ":" +
    //       std::to_string(_pos.cur().line) + "." +
    //       std::to_string(_pos.cur().col) +
    //       "\nUnknown error during global-scope parsing");
    // }
  }
}

void Parser::reconstruct(std::ostream &_where) const noexcept {
  // Disclose generation and object inclusions
  _where << "/*\n"
            "This file was generated by acorn version "
         << acorn_version << "\n"
         << "From source code in the Oak programming language\n"
         << "https://github.com/jorbDehmel/oak\n"
         << "The following objects will be including at "
            "compilation:\n";

  for (const auto &obj : settings.compile_settings().objects) {
    _where << "\t" << obj << "\n";
  }

  _where << "The following flags will be appended at compile "
            "time:\n";

  for (const auto &flag :
       settings.compile_settings().compile_flags) {
    _where << "\t" << flag << "\n";
  }

  _where << "The following flags will be appended at link "
            "time:\n";

  for (const auto &flag :
       settings.compile_settings().link_flags) {
    _where << "\t" << flag << "\n";
  }

  _where << "*/\n\n";

  // Include std header
  _where << "#include \"oak/std/std_oak_header.h\"\n";

  // Struct, fn, and enum signatures
  for (const auto &entry : scope_manager.in_order) {
    if (std::holds_alternative<StructInfo>(entry)) {
      _where << "struct " << std::get<StructInfo>(entry).name
             << ";\n";
    } else if (std::holds_alternative<EnumInfo>(entry)) {
      _where << "struct " << std::get<EnumInfo>(entry).name
             << ";\n";
    } else if (std::holds_alternative<FnInfo>(entry)) {
      const auto info = std::get<FnInfo>(entry);
      if (info.name == "main") {
        if (!info.tags.contains("file") ||
            info.tags.at("file") ==
                settings.compile_settings().entry_point) {
          _where << info.t.c_repr(info.name, true) << ";\n";
        }
      } else {
        _where << info.t.c_repr(info.name, false) << ";\n";
      }
    }
  }

  // Struct, fn, and enum definitions
  for (const auto &data : scope_manager.in_order) {
    if (std::holds_alternative<StructInfo>(data)) {
      auto info = std::get<StructInfo>(data);

      _where << "// #line " << info.tags["line"] << " \""
             << info.tags["file"] << "\"\n";

      _where << "struct " << info.name << " {\n";
      for (const auto &item : info.member_order) {
        _where << info.members.at(item).c_repr(item) << ";\n";
      }
      _where << "};\n";
    } else if (std::holds_alternative<EnumInfo>(data)) {
      auto info = std::get<EnumInfo>(data);

      _where << "// " << info.tags["file"] << ":"
             << info.tags["line"] << "\n";

      _where << "struct " << info.name << " {\nenum {\n";
      for (const auto &item : info.option_order) {
        _where << info.name << "_OPT_" << item << ",\n";
      }
      _where << "} __info;\nunion {\n";
      for (const auto &item : info.option_order) {
        _where << info.options.at(item).c_repr(item) << ";\n";
      }
      _where << "} __data;\n};\n";
    } else if (std::holds_alternative<FnInfo>(data)) {
      auto info = std::get<FnInfo>(data);
      if (info.tags.contains("casual") &&
          info.tags.at("casual") == "true") {
        continue;
      } else if (info.tags.contains("autogen") &&
                 info.tags.at("autogen") == "true") {
        _where << "// autogen\n";
      } else if (info.name == "main" &&
                 info.tags.contains("file") &&
                 info.tags.at("file") !=
                     settings.compile_settings().entry_point) {
        continue;
      }

      _where << "// " << info.tags["file"] << ":"
             << info.tags["line"] << "\n";
      _where << info.t.c_repr(info.name, info.name == "main");
      if (info.n.children.size() == 1) {
        // Single statement
        _where << "{";
        ::reconstruct(info.n, _where);
        _where << "}";
      } else {
        // Scope
        ::reconstruct(info.n, _where);
      }
      _where << "\n";
    }
  }
}

void Parser::dump(std::ostream &_where,
                  TokenStream &_pos) const noexcept {
  debug_print_pos(__FUNCTION__, _pos);

  _where << "// Lexed contents of file " << _pos.cur().file;

  intmax_t cur_line = 0;
  for (const auto &cur : _pos) {
    if (cur_line == cur.line) {
      _where << ' ' << cur.text;
    } else {
      _where << '\n' << cur_line << "\t|";
    }
  }

  _where << "\n// Attempted reconstruction\n";

  try {
    reconstruct(_where);
  } catch (std::runtime_error &e) {
    _where << "// FAILURE: " << e.what() << '\n';
  } catch (...) {
    _where << "// UNKNOWN FAILURE\n";
  }

  _where << "// Entries:\n";
  for (const auto &data : scope_manager.in_order) {
    if (std::holds_alternative<StructInfo>(data)) {
      const auto info = std::get<StructInfo>(data);
      _where << info.name << " [";
      for (auto it = info.tags.begin(); it != info.tags.end();
           ++it) {
        if (it != info.tags.begin()) {
          _where << ", ";
        }
        _where << "{\"" << it->first << "\": \"" << it->second
               << "\"}";
      }
      _where << "]\n";
      for (const auto &member : info.member_order) {
        _where << "\t"
               << info.members.at(member).oak_repr(member)
               << '\n';
      }
    } else if (std::holds_alternative<EnumInfo>(data)) {
      const auto info = std::get<EnumInfo>(data);
      _where << info.name << " [";
      for (auto it = info.tags.begin(); it != info.tags.end();
           ++it) {
        if (it != info.tags.begin()) {
          _where << ", ";
        }
        _where << "{\"" << it->first << "\": \"" << it->second
               << "\"}";
      }
      _where << "]\n";
      for (const auto &member : info.option_order) {
        _where << "\t"
               << info.options.at(member).oak_repr(member)
               << '\n';
      }
    } else {
      const auto info = std::get<FnInfo>(data);
      _where << info.name << ":\n\t"
             << info.t.oak_repr(info.name) << '\n';
    }
  }
}

void Parser::parse_function(
    const std::list<std::string> &_names, TokenStream &_pos) {
  debug_print_pos(__FUNCTION__, _pos);

  // Finish parsing type
  Type t = parse_type(_pos);

  // Special case type restrictions
  for (const auto &name : _names) {
    if (name == "main") {
      const auto args = t.fn_args();
      const auto ret = t.fn_return_type();
      if (!args.empty()) {
        if (args.size() != 2) {
        } else if (!args.front().second.exact_match(
                       Type({"i32"}))) {
          throw std::runtime_error("If provided, " + name +
                                   "'s first argument (argc) "
                                   "should be of type i32");
        } else if (!args.back().second.exact_match(Type(ASTNode(
                       "[]",
                       {ASTNode("[]", {ASTNode("i8")})})))) {
          throw std::runtime_error("If provided, " + name +
                                   "'s second argument (argv) "
                                   "should be of type [][]i8");
        }
      }
      if (!ret.exact_match(Type({"i32"})) &&
          !ret.exact_match(Type({"void"}))) {
        throw std::runtime_error(
            "main must have a return type of i32 or void");
      }
    } else if (name == "New" || name == "Del") {
      const auto args = t.fn_args();
      const auto ret = t.fn_return_type();
      if (args.size() != 1) {
        throw std::runtime_error(
            name + " must take only one argument: A pointer to "
                   "the object to act upon");
      } else if (!args.front().second.is_ptr()) {
        throw std::runtime_error(
            name + " must take a pointer as its argument");
      } else if (!ret.exact_match(Type({"void"}))) {
        throw std::runtime_error(
            name + " must have a void return type");
      }
    }
  }

  FnInfo to_add;
  to_add.t = t;
  to_add.tags["file"] = _pos.cur().file;
  to_add.tags["line"] = std::to_string(_pos.cur().line);
  to_add.tags["col"] = std::to_string(_pos.cur().col);

  // Either signature or implementation
  if (_pos.cur() == ";") {
    // Signature
    to_add.tags["casual"] = "true";
    _pos.next();
  } else {
    // Implementation

    // Signatures for recursion
    FnInfo temp_info = to_add;
    temp_info.tags["casual"] = "true";
    for (const auto &name : _names) {
      temp_info.name = name;
      scope_manager.add(name, temp_info);
    }

    // Push stack frame w/ args
    scope_manager.push_frame();
    auto args = t.fn_args();
    for (const auto &p : args) {
      scope_manager.add(p.first, p.second);
    }

    // Adjust return type stack
    settings.compile_settings().cur_return_type.push_back(
        t.fn_return_type());

    // Parse fn body
    to_add.n = parse_statement(_pos);

    // Restore return type
    settings.compile_settings().cur_return_type.pop_back();

    // Pop stack frame WITHOUT CALLING ARGUMENT DESTRUCTORS
    scope_manager.pop_frame();
  }

  // Add the functions
  for (const auto &name : _names) {
    to_add.name = name;
    scope_manager.add(name, to_add);
  }
}

std::list<std::pair<std::string, Type>>
Parser::parse_members(TokenStream &_pos) {
  debug_print_pos(__FUNCTION__, _pos);

  // Where to write output
  std::list<std::pair<std::string, Type>> out;

  // For keeping track of used names
  std::set<std::string> all_names;

  _pos.expect({"{"});

  while (_pos.cur() != "}") {
    // One or more comma-separated names
    std::list<std::string> current_names;

    // Mandatory name
    current_names.push_back(_pos.cur_next());

    // Optional names
    while (_pos.cur() == ",") {
      _pos.next();
      current_names.push_back(_pos.cur_next());
    }

    // Type
    _pos.expect({":"});
    Type t = parse_type(_pos);

    // Add these members
    for (const auto &name : current_names) {
      // Safety check for collisions
      if (all_names.contains(name)) {
        throw std::runtime_error(
            "Cannot have multiple members with name '" + name +
            "'");
      }
      all_names.insert(name);
      out.push_back({name, t});
    }

    // Advance past vestigial commas
    while (_pos.cur() == ",") {
      _pos.next();
    }
  }
  _pos.expect({"}"});
  return out;
}

void Parser::parse_template(
    const std::list<std::string> &_names,
    const std::list<std::string> &_suspensions,
    TokenStream &_pos) {
  debug_print_pos(__FUNCTION__, _pos);

  const auto start_tok = _pos.cur();
  std::list<Token> guts;

  int count = 0;
  if (_pos.cur() != "{") {
    throw std::runtime_error(
        "Malformed template block: Expected '{', but saw '" +
        _pos.cur().text + "'");
  }
  do {
    if (_pos.done()) {
      throw std::runtime_error(
          "Reached EOF before template '}'");
    } else if (_pos.cur() == "{") {
      ++count;
      if (count == 1) {
        _pos.next();
        continue;
      }
    } else if (_pos.cur() == "}") {
      --count;
      if (count == 0) {
        break;
      }
    }
    guts.push_back(_pos.cur());
    _pos.next();
  } while (count != 0);

  for (const auto &name : _names) {
    TemplateInfo info(start_tok.file, start_tok.line,
                      start_tok.col, name);
    info.generics = _suspensions;
    info.instantiate_block = guts;
    scope_manager.add(name, info);
  }
}

Type Parser::parse_type(TokenStream &_pos) {
  debug_print_pos(__FUNCTION__, _pos);

  const auto t = _pos.cur_next();
  if (t == "type!") {
    _pos.expect({"("});
    const auto to_get_type_of = parse_object(_pos);
    _pos.expect({")"});
    return ::type(to_get_type_of);
  } else if (t == "[") {
    // arr
    if (_pos.cur() == "]") {
      // unsized arr
      _pos.next();
      return ASTNode("[]", {parse_type(_pos)});
    } else {
      // sized arr
      const auto s = parse_object(_pos);
      _pos.expect({"]"});
      return ASTNode("[]", {s, parse_type(_pos)});
    }
  } else if (t == "^") {
    // Pointer
    return ASTNode("^", {parse_type(_pos)});
  } else if (t == "(") {
    // Function
    ASTNode args("_");
    while (_pos.cur() != ")") {
      const std::string name = _pos.cur();
      _pos.next();
      _pos.expect({":"});
      const Type arg_type = parse_type(_pos);
      args.children.push_back(
          ASTNode("arg", {ASTNode(name), arg_type}));
      while (_pos.cur() == ",") {
        _pos.next();
      }
    }
    _pos.expect({")"});

    Type ret_type = ASTNode("void");
    if (_pos.cur() == "->") {
      _pos.next();
      ret_type = parse_type(_pos);
    }
    return ASTNode("->", {args, ret_type});
  } else {
    // atomic
    _pos.prev();
    return ASTNode(parse_id(_pos));
  }
}

std::string Parser::parse_id(TokenStream &_pos) {
  debug_print_pos(__FUNCTION__, _pos);

  std::string name = _pos.cur_next().text;

  if (_pos.cur().text == "<") {
    TemplateInfo::Substitution replacements;
    std::list<std::string> cur;
    int count = 0;
    do {
      if (_pos.cur() == "<") {
        ++count;
        if (count == 1) {
          _pos.next();
          continue;
        }
      } else if (_pos.cur() == ">") {
        --count;
        if (count == 0) {
          replacements.push_back(cur);
          _pos.next();
          break;
        }
      }

      if (count == 1 && _pos.cur() == ",") {
        replacements.push_back(cur);
        cur.clear();
      } else {
        cur.push_back(_pos.cur());
      }

      _pos.next();
    } while (!_pos.done() && count != 0);

    // Instantiate first
    const auto res = scope_manager.get(name);
    if (!res.has_value()) {
      throw std::runtime_error("No templates exist named '" +
                               name + "'");
    }
    if (!std::holds_alternative<ScopeManager::TemplValue>(
            res.value())) {
      throw std::runtime_error("'" + name +
                               "' is not a template");
    }
    auto templates =
        std::get<ScopeManager::TemplValue>(res.value());

    bool instantiated = false;
    std::vector<std::pair<std::string, TemplateInfo>>
        failure_log;
    for (auto it = templates.rbegin(); it != templates.rend();
         ++it) {
      std::string err_msg;
      instantiated = instantiate(*it, replacements, err_msg);
      if (instantiated) {
        break;
      }
      failure_log.push_back({err_msg, *it});
    }
    if (!instantiated) {
      for (uint i = 0; i < failure_log.size(); ++i) {
        settings.ostream
            << "Failure " << i << " ("
            << failure_log.at(i).second.name << " from "
            << failure_log.at(i).second.path << ":"
            << failure_log.at(i).second.line << "."
            << failure_log.at(i).second.col << "):\n"
            << failure_log.at(i).first << "\n"
            << "End failure " << i << "\n";
      }
      throw std::runtime_error(
          "Failed to instantiate any templates for '" + name +
          "'");
    }

    // These must always be followed by a true name
    name = build_generic_prefix(name, replacements) +
           _pos.cur_next().text;
  }
  return name;
}

void Parser::parse_struct(const std::list<std::string> &_names,
                          TokenStream &_pos) {
  debug_print_pos(__FUNCTION__, _pos);

  // The struct info to populate
  StructInfo to_add;
  to_add.tags["file"] = _pos.cur().file;
  to_add.tags["line"] = std::to_string(_pos.cur().line);
  to_add.tags["col"] = std::to_string(_pos.cur().col);

  // Casual def
  if (_pos.cur() == ";") {
    to_add.tags["casual"] = "true";
    _pos.next();
  }

  // Declaration
  else if (_pos.cur() == "{") {
    const auto members = parse_members(_pos);
    for (const auto &member : members) {
      to_add.member_order.push_back(member.first);
      to_add.members[member.first] = member.second;
    }
  }

  // Invalid
  else {
    throw std::runtime_error("Invalid struct declaration: "
                             "Expected ';' or '{' but saw '" +
                             _pos.cur().text + "'");
  }

  // Add these entries
  for (const auto &name : _names) {
    check_camelcase(settings, "Struct", name, _pos.cur());

    to_add.name = name;
    scope_manager.add(name, to_add);

    // Constructor and destructor autogen
    auto default_constructor =
        get_default_constructor(to_add, _pos.cur());
    auto default_destructor =
        get_default_destructor(to_add, _pos.cur());

    // Add the autogen constructors
    scope_manager.add("New", default_constructor);
    scope_manager.add("Del", default_destructor);
  }
}

ASTNode Parser::parse_case(const EnumInfo &_enum_type,
                           TokenStream &_pos,
                           const bool &_is_mutable) {
  debug_print_pos(__FUNCTION__, _pos);
  const std::string case_type = _pos.cur_next();
  if (case_type == "case") {
    const std::string case_name = _pos.cur_next();
    _pos.expect({"("});
    const auto passed_name = _pos.cur_next();
    _pos.expect({":"});
    const Type observed_type = parse_type(_pos);
    _pos.expect({")"});

    if (!_enum_type.options.contains(case_name)) {
      throw std::runtime_error("'" + case_name +
                               "' is not a valid enum option");
    }
    const Type expected_type = _enum_type.options.at(case_name);

    // Arg type check
    if (_is_mutable) {
      // Pointer or exact allowed
      if (!observed_type.exact_match(expected_type) &&
          !observed_type.deref().exact_match(expected_type)) {
        throw std::runtime_error(
            "Invalid type for mutable case '" + case_name +
            "': Expected '" + expected_type.oak_repr() +
            "' (or a pointer to that), but saw '" +
            observed_type.oak_repr() + "'");
      }
    } else {
      // Only exact allowed
      if (!observed_type.exact_match(expected_type)) {
        throw std::runtime_error(
            "Invalid type for immutable case '" + case_name +
            "': Expected '" + expected_type.oak_repr() +
            "', but saw '" + observed_type.oak_repr() + "'");
      }
    }

    // Push to locals stack
    scope_manager.push_frame();
    scope_manager.add(passed_name, observed_type);

    // Push frame to be popped
    scope_manager.push_frame();

    // Statement
    ASTNode statement = parse_statement(_pos);

    // Pop frame
    const auto to_destroy = scope_manager.pop_frame();

    // Prepare destructor block
    ASTNode destructor_block = ASTNode("statement");
    for (const auto &obj : to_destroy) {
      assert(obj.text == "object");
      destructor_block.children.push_back(ASTNode(
          "statement", {get_function_call_node("Del", {obj})}));
    }

    // Insert destructor block
    statement.children.push_back(destructor_block);

    // Pop from locals stack WITHOUT CALLING DESTRUCTOR ON
    // CAPTURE
    scope_manager.pop_frame();

    return ASTNode("case",
                   {ASTNode(case_name), ASTNode(passed_name),
                    observed_type, statement});
  } else if (case_type == "else") {
    return ASTNode("else", {ASTNode(parse_statement(_pos))});
  } else {
    throw std::runtime_error(
        "Error within match statement: Expected 'case' or "
        "'else', but saw '" +
        case_type + "'");
  }
}

void Parser::parse_enum(const std::list<std::string> &_names,
                        TokenStream &_pos) {
  debug_print_pos(__FUNCTION__, _pos);

  // The enum info to populate
  EnumInfo to_add;
  to_add.tags["file"] = _pos.cur().file;
  to_add.tags["line"] = std::to_string(_pos.cur().line);
  to_add.tags["col"] = std::to_string(_pos.cur().col);

  // Casual def
  if (_pos.cur() == ";") {
    to_add.tags["casual"] = "true";
    _pos.next();
  }

  // Declaration
  else if (_pos.cur() == "{") {
    const auto members = parse_members(_pos);
    for (const auto &member : members) {
      to_add.option_order.push_back(member.first);
      to_add.options[member.first] = member.second;
    }
  }

  // Invalid
  else {
    throw std::runtime_error("Invalid enum declaration: "
                             "Expected ';' or '{' but saw '" +
                             _pos.cur().text + "'");
  }

  // Add these entries
  for (const auto &name : _names) {
    check_camelcase(settings, "Enum", name, _pos.cur());

    // Add the enum part
    to_add.name = name;
    scope_manager.add(name, to_add);

    // Wrappers
    for (const auto &p : get_wrappers(to_add, _pos.cur())) {
      scope_manager.add(p.name, p);
    }

    // Constructor
    auto default_constructor =
        get_default_constructor(to_add, _pos.cur());

    // Create destructor
    auto default_destructor =
        get_default_destructor(to_add, _pos.cur());

    // Note: Enum new and del cannot be overloaded, so they
    // aren't marked autogen
    scope_manager.add("New", default_constructor);
    scope_manager.add("Del", default_destructor);
  }
}

ASTNode Parser::parse_function_call(TokenStream &_pos) {
  debug_print_pos(__FUNCTION__, _pos);

  const std::string unmangled_name = parse_id(_pos);
  _pos.expect({"("});

  // Special case: size!
  if (unmangled_name == "size!") {
    // One type argument
    ASTNode out("raw_c_format");
    out.children.push_back(
        ASTNode("sizeof(" + parse_type(_pos).c_repr() + ")"));
    out.children.push_back(Type({"uint"}));
    out.children.push_back(ASTNode("_", {}));
    _pos.expect({")"});
    return out;
  }

  // Args
  std::list<ASTNode> args;
  while (_pos.cur() != ")") {
    if (_pos.cur() != ",") {
      args.push_back(parse_object(_pos));
    } else {
      _pos.next();
    }
  }
  _pos.expect({")"});

  // Return resolved fn node
  return get_function_call_node(unmangled_name, args);
}

ASTNode Parser::parse_object(TokenStream &_pos) {
  debug_print_pos(__FUNCTION__, _pos);

  // Open parenthesis immediately: No-capture lambda
  if (_pos.cur() == "(") {
    // Create name
    uint lambda_counter = 1;
    while (scope_manager.contains(
        "__oak_lambda_" + std::to_string(lambda_counter))) {
      ++lambda_counter;
    }
    const std::string lambda_name =
        "__oak_lambda_" + std::to_string(lambda_counter);

    // Parse function
    scope_manager.push_capture_frame();
    parse_function({lambda_name}, _pos);

    const auto captures = scope_manager.get_captures();
    for (const auto &capture : captures) {
      const auto l = _pos.cur();
      settings.warn(l.file, l.line, l.col,
                    "Illegal capture " + capture);
    }

    scope_manager.pop_frame();

    // Return a fn pointer to that lambda
    const auto t =
        scope_manager.at<ScopeManager::FnValue>(lambda_name)
            .back()
            .t;
    return ASTNode("object",
                   {t, ASTNode(t.mangle(lambda_name))});
  }

  // Open parenthesis follows: Function call
  else if (_pos.peek().text == "(") {
    return parse_function_call(_pos);
  }

  uint derefs = 0;
  while (!_pos.done() && _pos.cur() == "^") {
    ++derefs;
    _pos.next();
    if (_pos.done()) {
      throw std::runtime_error(
          "'^' operator must operate on a variable.");
    }
  }

  Token name = _pos.cur_next();

  // Literal check
  const auto literal_type = get_literal_type(name);
  if (literal_type.has_value()) {
    return ASTNode("object",
                   {literal_type.value(), ASTNode(name)});
  }

  // Variable check
  const auto value = scope_manager.get(name);
  if (!value.has_value()) {
    throw std::runtime_error("Failed to resolve object '" +
                             name.text + "'");
  }

  // Variable instance: Not fn ptr
  if (std::holds_alternative<Type>(value.value())) {
    Type t = std::get<Type>(value.value());
    if (derefs > 0) {
      for (uint i = 0; i < derefs; ++i) {
        name.text = "(*" + name.text + ")";
        if (t.is_ptr()) {
          t = t.deref();
        } else {
          throw std::runtime_error(
              "Cannot dereference non-pointer type '" +
              t.oak_repr() + "'");
        }
      }
    }

    // Member access
    while (_pos.cur().text == ".") {
      _pos.next(); // Pointing at member name
      const auto member_name = _pos.cur_next().text;
      while (t.is_ptr()) {
        name.text = "(*" + name.text + ")";
        t = t.deref();
      }
      const auto info =
          scope_manager.get(t.struct_name()).value();
      if (std::holds_alternative<StructInfo>(info)) {
        const StructInfo struct_info =
            std::get<StructInfo>(info);
        if (!struct_info.members.contains(member_name)) {
          throw std::runtime_error(
              "Struct '" + t.struct_name() +
              "' has no member '" + member_name + "'");
        }
        t = struct_info.members.at(member_name);
      } else {
        const EnumInfo enum_info = std::get<EnumInfo>(info);
        if (!enum_info.options.contains(member_name)) {
          throw std::runtime_error("Enum '" + t.struct_name() +
                                   "' has no option '" +
                                   member_name + "'");
        }
        t = enum_info.options.at(member_name);
      }
      name.text += "." + member_name;
    }
    return ASTNode("object", {t, ASTNode(name)});
  }

  // If we're out here, it should be a fn
  if (!std::holds_alternative<ScopeManager::FnValue>(
          value.value())) {
    throw std::runtime_error(
        "Symbol '" + name.text +
        "' is not a variable instance or function");
  }

  auto l = std::get<ScopeManager::FnValue>(value.value());
  if (l.size() != 1) {
    throw std::runtime_error(
        "Function pointers can only be taken when the target "
        "function name has no type overloads");
  }

  // Fn ptr
  auto instance = l.front();
  return ASTNode(
      "object",
      {instance.t.ref(),
       ASTNode("(&" + instance.t.mangle(name) + ")")});
}

ASTNode Parser::parse_statement(
    TokenStream &_pos,
    const std::optional<Type> &_return_type) {
  debug_print_pos(__FUNCTION__, _pos);

  // Delegate macro calls
  const auto name = _pos.cur().text;
  if (name.ends_with('!')) {
    if (name == "c!") {
      _pos.next();
      _pos.expect({"("});
      const auto arg =
          ASTNode(strip_string_literal(_pos.cur_next().text));
      _pos.expect({")"});

      const ASTNode out = ASTNode(
          "statement",
          {ASTNode("raw_c_format",
                   {arg, ASTNode("void"), ASTNode("_", {})})});

      if (settings.debug) {
        std::cout << __FILE__ << ":" << __LINE__
                  << "> Parsed statement " << out << '\n';
        debug_print_pos(__FUNCTION__, _pos);
      }

      return out;
    } else {
      replace_macro(_pos);
      if (settings.debug) {
        std::cout << __FILE__ << ":" << __LINE__
                  << "> Parsed null statement\n";
        debug_print_pos(__FUNCTION__, _pos);
      }
      return ASTNode("null");
    }
  } else if (name == ";") {
    // Unit statement
    _pos.next();
    return ASTNode("null");
  } else if (name == "let") {
    // Variable declaration
    // Collect names
    std::list<std::string> names;
    bool is_macro = false;

    // Gather names, flag if macro
    do {
      // Get past 'let' or ','
      _pos.next();
      const std::string name = _pos.cur_next();
      names.push_back(name);
      if (name.ends_with("!")) {
        is_macro = true;
      }
    } while (!_pos.done() && _pos.cur() == ",");

    // Generic declaration
    const std::string first_after_name = _pos.cur();
    if (first_after_name == "<") {
      // Zero or more comma-separated generics
      std::list<std::string> generics;
      if (is_macro) {
        throw std::runtime_error("Macros cannot be templated");
      }
      do {
        _pos.next();
        const auto t = _pos.cur_next();
        check_camelcase(settings, "Generic", t.text, t);
        generics.push_back(t);
      } while (!_pos.done() && _pos.cur() == ",");
      _pos.expect({">"});
      parse_template(names, generics, _pos);
      return ASTNode("null");
    }

    // Explicitly typed declaration
    else if (first_after_name == ":") {
      // Variables, structs, and enums
      _pos.next();
      if (_pos.cur() == "struct") {
        // Struct
        _pos.next();
        parse_struct(names, _pos);
        return ASTNode("null");
      } else if (_pos.cur() == "enum") {
        // enum
        _pos.next();
        parse_enum(names, _pos);
        return ASTNode("null");
      } else {
        // Variable
        Type t = parse_type(_pos);
        validate_type(t);

        ASTNode new_calls("_");
        ASTNode names_node("_");
        for (const auto &name : names) {
          names_node.children.push_back(ASTNode(name));
          scope_manager.add(name, t);
          const ASTNode upon("object", {t, ASTNode(name)});

          // Add `New` call
          new_calls.children.push_back(
              get_function_call_node("New", {upon}));
        }

        // auto decl = ASTNode("let", {names, new_calls, type})
        const ASTNode stmt_out(
            "statement",
            {ASTNode("let", {names_node, new_calls, t})});

        if (_pos.cur() == "=") {
          // Instantiation-assignment copy
          throw std::runtime_error(
              "Instantiation-assignment combination operator "
              "(let A: B = C;) is unimplemented");
        }

        if (settings.debug) {
          std::cout << __FILE__ << ":" << __LINE__
                    << "> Parsed statement " << stmt_out
                    << '\n';
          debug_print_pos(__FUNCTION__, _pos);
        }

        return stmt_out;
      }
      return ASTNode("null");
    } else if (first_after_name == "(") {
      // Function or function-style macro declaration
      if (is_macro) {
        parse_macro(
            _pos,
            settings.compile_settings().preprocess_pass_limit,
            names);
        return ASTNode("null");
      } else {
        // Function
        parse_function(names, _pos);
        return ASTNode("null");
      }
    } else if (first_after_name == "=") {
      // Inline macro or implicitly typed declaration
      if (is_macro) {
        // Inline macro definition
        parse_macro(
            _pos,
            settings.compile_settings().preprocess_pass_limit,
            names);
        return ASTNode("null");
      } else {
        // let A = B;
        _pos.next();
        const auto copy_from = parse_object(_pos);
        const Type t = ::type(copy_from);
        validate_type(t);

        // Instantiate
        ASTNode names_node("_");
        ASTNode new_calls("_");
        for (const auto &name : names) {
          names_node.children.push_back(ASTNode(name));
          scope_manager.add(name, t);
          const ASTNode upon("object", {t, ASTNode(name)});

          // Literal `New` call
          new_calls.children.push_back(
              get_function_call_node("New", {upon}));

          // Literal `Copy` call
          new_calls.children.push_back(get_function_call_node(
              "Copy", {upon, copy_from}));
        }

        // auto decl = ASTNode("let", {names, new_calls, type})
        const auto out = ASTNode(
            "statement",
            {ASTNode("let", {names_node, new_calls, t})});

        if (settings.debug) {
          std::cout << __FILE__ << ":" << __LINE__
                    << "> Parsed statement " << out << '\n';
          debug_print_pos(__FUNCTION__, _pos);
        }

        return out;
      }
    }

    throw std::runtime_error(
        "Unexpected token '" + first_after_name +
        "' after name(s) in 'let' statement");
  } else if (name == "{") {
    // Scope
    ASTNode out("statement");
    scope_manager.push_frame();
    _pos.next();
    while (!_pos.done() && _pos.cur() != "}") {
      out.children.push_back(parse_statement(_pos));
    }
    _pos.expect({"}"});

    // Pop frame
    const auto to_destroy = scope_manager.pop_frame();

    // Prepare destructor block
    ASTNode destructor_block = ASTNode("statement");
    for (const auto &obj : to_destroy) {
      assert(obj.text == "object");
      destructor_block.children.push_back(ASTNode(
          "statement", {get_function_call_node("Del", {obj})}));
    }

    // Insert destructor block
    out.children.push_back(destructor_block);

    if (settings.debug) {
      std::cout << __FILE__ << ":" << __LINE__
                << "> Parsed statement " << out << '\n';
      debug_print_pos(__FUNCTION__, _pos);
    }

    return out;
  } else if (name == "if") {
    // If statement
    _pos.next();
    bool has_parenthesis = true;
    if (_pos.cur() != "(") {
      has_parenthesis = false;
    } else {
      _pos.next();
    }

    ASTNode out("if");
    const ASTNode condition = parse_object(_pos);
    out.children.push_back(condition);

    // Castable type check
    const Type condition_type = ::type(condition);
    if (!condition_type.cast_match(Type(ASTNode("bool")))) {
      throw std::runtime_error("Statement condition type '" +
                               condition_type.oak_repr() +
                               "' is not castable to bool.");
    }

    if (has_parenthesis) {
      _pos.expect({")"});
    }

    // Body
    out.children.push_back(parse_statement(_pos));

    // Optional else clause
    if (!_pos.done() && _pos.cur() == "else") {
      _pos.next();
      out.children.push_back(parse_statement(_pos));
    }

    const auto true_out = ASTNode("statement", {out});

    if (settings.debug) {
      std::cout << __FILE__ << ":" << __LINE__
                << "> Parsed statement " << true_out << '\n';
      debug_print_pos(__FUNCTION__, _pos);
    }

    return true_out;
  } else if (name == "while") {
    // While loop
    _pos.next();
    bool has_parenthesis = true;
    if (_pos.cur() != "(") {
      has_parenthesis = false;
    } else {
      _pos.next();
    }

    ASTNode out("while");
    const ASTNode condition = parse_object(_pos);
    out.children.push_back(condition);

    // Type check
    const Type condition_type = ::type(condition);
    if (!condition_type.cast_match(Type(ASTNode("bool")))) {
      throw std::runtime_error("Statement condition type '" +
                               condition_type.oak_repr() +
                               "' is not castable to bool.");
    }

    if (has_parenthesis) {
      _pos.expect({")"});
    }

    out.children.push_back(parse_statement(_pos));

    const auto true_out = ASTNode("statement", {out});
    if (settings.debug) {
      std::cout << __FILE__ << ":" << __LINE__
                << "> Parsed statement " << true_out << '\n';
      debug_print_pos(__FUNCTION__, _pos);
    }

    return true_out;
  } else if (_pos.cur() == "match") {
    // Match statement
    _pos.next();
    bool has_parenthesis = true;
    if (_pos.cur() != "(") {
      has_parenthesis = false;
    } else {
      _pos.next();
    }

    // Target is an enum
    ASTNode target = parse_object(_pos);
    Type target_type = ::type(target);

    const bool is_mutable = target_type.is_ptr();
    if (is_mutable) {
      target_type = target_type.deref();
    }

    const std::string enum_name = target_type.struct_name();
    const EnumInfo info = scope_manager.at<EnumInfo>(enum_name);

    if (has_parenthesis) {
      _pos.expect({")"});
    }
    if (is_mutable) {
      target = ASTNode("raw_c_format",
                       {ASTNode("(*%)"), ASTNode(enum_name),
                        ASTNode("_", {target})});
    }

    _pos.expect({"{"});
    ASTNode branches("_");
    while (_pos.cur() != "}") {
      branches.children.push_back(
          parse_case(info, _pos, is_mutable));
    }
    _pos.expect({"}"});
    const ASTNode out("match",
                      {target, branches, ASTNode(enum_name),
                       ASTNode(is_mutable ? "true" : "false")});

    const auto true_out = ASTNode("statement", {out});
    if (settings.debug) {
      std::cout << __FILE__ << ":" << __LINE__
                << "> Parsed statement " << true_out << '\n';
      debug_print_pos(__FUNCTION__, _pos);
    }

    return true_out;
  } else if (_pos.cur() == "return") {
    // Return statement
    ASTNode out("return");
    _pos.next();
    const Type expected_return_type =
        settings.compile_settings().cur_return_type.back();
    if (_pos.cur() != ";") {
      const ASTNode val = parse_object(_pos);
      out.children.push_back(val);
      const Type val_type = ::type(val);
      if (!expected_return_type.exact_match(val_type)) {
        throw std::runtime_error(
            "Invalid return type '" + val_type.oak_repr() +
            "' for fn w/ return "
            "type '" +
            expected_return_type.oak_repr() + "'");
      }
    } else if (!expected_return_type.exact_match(
                   ASTNode("void"))) {
      throw std::runtime_error(
          "Invalid return type 'void' for fn w/ return type "
          "'" +
          expected_return_type.oak_repr() + "'");
    }

    const auto true_out = ASTNode("statement", {out});

    if (settings.debug) {
      std::cout << __FILE__ << ":" << __LINE__
                << "> Parsed statement " << true_out << '\n';
      debug_print_pos(__FUNCTION__, _pos);
    }

    return true_out;
  } else {
    // Else, delegate as function call
    const auto out =
        ASTNode("statement", {parse_function_call(_pos)});
    if (settings.debug) {
      std::cout << __FILE__ << ":" << __LINE__
                << "> Parsed statement " << out << '\n';
      debug_print_pos(__FUNCTION__, _pos);
    }
    return out;
  }
}

ASTNode Parser::get_function_call_node(
    const std::string &_unmangled_name,
    const std::list<ASTNode> &_args) {
  debug_print_pos(__FUNCTION__);

  // Array access via the 'Get' operator
  if (_unmangled_name == "Get" && _args.size() == 2 &&
      (Type(::type(_args.back())).cast_match(Type({"u128"})) ||
       Type(::type(_args.back())).cast_match(Type({"i128"}))) &&
      Type(::type(_args.front())).is_arr()) {
    return ASTNode(
        "[]",
        {_args.front(), _args.back(),
         Type(::type(_args.front())).deref_allow_arrays()});
  }

  // alloc
  else if (_unmangled_name == "alloc") {
    // 1-arg
    if (_args.size() == 1) {
      if (!Type(::type(_args.front())).is_ptr()) {
        throw std::runtime_error(
            "Expected pointer type for alloc(into), instead "
            "saw '" +
            Type(::type(_args.front())).oak_repr() + "'");
      }

      const Type t = ::type(_args.front());
      return ASTNode(
          "raw_c_format",
          {ASTNode("% = (" + t.c_repr() + ") malloc(sizeof(" +
                   t.deref().c_repr() +
                   ")); assert(% != NULL)"),
           ASTNode("void"),
           ASTNode("_", {_args.front(), _args.front()})});
    }

    // 2-arg
    else if (_args.size() == 2) {
      const auto t = Type(::type(_args.front()));
      if (!t.is_unsized_arr()) {
        throw std::runtime_error(
            "Expected unsized array type for alloc(into, "
            "size), instead saw '" +
            t.oak_repr() + "'");
      }

      return ASTNode(
          "raw_c_format",
          {ASTNode("% = (" + t.c_repr() +
                   ") calloc(%, sizeof(" + t.c_repr() +
                   ")); assert(% != NULL)"),
           ASTNode("void"),
           ASTNode("_", {_args.front(), _args.back(),
                         _args.front()})});
    }

    // Error case
    else {
      throw std::runtime_error("alloc takes 1 or 2 args.");
    }
  }

  // free
  else if (_unmangled_name == "free") {
    const Type t = ::type(_args.front());
    if (_args.size() != 1 ||
        !(t.is_ptr() || t.is_unsized_arr())) {
      throw std::runtime_error(
          "Expected pointer or unsized array type for "
          "free(to_free), instead saw '" +
          t.oak_repr() + "'");
    }

    return ASTNode("raw_c_format",
                   {ASTNode("free((void *)(%))"),
                    ASTNode("void"),
                    ASTNode("_", {_args.front()})});
  }

  // New on pointer or unsized array types
  else if (_unmangled_name == "New" && _args.size() == 1 &&
           (Type(::type(_args.front())).is_ptr() ||
            Type(::type(_args.front())).is_unsized_arr())) {
    return ASTNode("raw_c_format",
                   {ASTNode("% = 0"), ASTNode("void"),
                    ASTNode("_", {_args.front()})});
  }

  // New on sized array types
  else if (_unmangled_name == "New" && _args.size() == 1 &&
           Type(::type(_args.front())).is_sized_arr()) {

    std::cout << __FILE__ << ":" << __LINE__ << "> "
              << _args.front() << '\n';

    const auto size = std::stoull(
        Type(::type(_args.front())).sized_arr_size().text);

    ASTNode out("statement");
    for (uint i = 0; i < size; ++i) {
      ASTNode arg("raw_c_format");
      arg.children.push_back(
          ASTNode("(%)[" + std::to_string(i) + "]"));
      arg.children.push_back(
          Type(::type(_args.front())).deref());
      arg.children.push_back(ASTNode("_", {_args.front()}));

      out.children.push_back(
          get_function_call_node("New", {arg}));
    }
    return out;
  }

  // New on atomic types
  else if (_unmangled_name == "New" && _args.size() == 1 &&
           Type::is_built_in_type(::type(_args.front()))) {
    return ASTNode("raw_c_format",
                   {ASTNode("% = 0;"), ASTNode("void"),
                    ASTNode("_", {_args.front()})});
  }

  // Del on atomic types
  else if (_unmangled_name == "Del" && _args.size() == 1 &&
           Type::is_built_in_type(::type(_args.front()))) {
    return ASTNode("null");
  }

  // Del on pointer or unsized array types
  else if (_unmangled_name == "Del" && _args.size() == 1 &&
           (Type(::type(_args.front())).is_ptr() ||
            Type(::type(_args.front())).is_unsized_arr())) {
    return ASTNode("null");
  }

  // Del on sized array types
  else if (_unmangled_name == "Del" && _args.size() == 1 &&
           Type(::type(_args.front())).is_sized_arr()) {
    const auto size = std::stoull(
        Type(::type(_args.front())).sized_arr_size().text);

    ASTNode out("statement");
    for (uint i = 0; i < size; ++i) {
      ASTNode arg("raw_c_format",
                  {ASTNode("(%)[" + std::to_string(i) + "]"),
                   Type(::type(_args.front())).deref(),
                   ASTNode("_", {_args.front()})});
      out.children.push_back(
          get_function_call_node("Del", {arg}));
    }
    return out;
  }

  // Pointer copy
  else if (_unmangled_name == "Copy" && _args.size() == 2 &&
           Type(::type(_args.back())).is_ptr() &&
           Type(::type(_args.front()))
               .cast_match(::type(_args.back()))) {
    return ASTNode(
        "raw_c_format",
        {ASTNode("% = %"), ASTNode("void"),
         ASTNode("_", {_args.front(), _args.back()})});
  }

  // Special case: Local fn pointer
  else if (scope_manager.contains(_unmangled_name) &&
           std::holds_alternative<Type>(
               scope_manager.get(_unmangled_name).value())) {
    const Type local_var_type =
        scope_manager.at<Type>(_unmangled_name);

    if (local_var_type.is_fn_ptr()) {
      const auto fn_type = local_var_type.deref();
      const auto needed_args = fn_type.fn_args();

      if (_args.size() != needed_args.size()) {
        throw std::runtime_error(
            "Expected " + std::to_string(needed_args.size()) +
            " args in fn pointer call, but saw " +
            std::to_string(_args.size()));
      }

      auto args_at_i = _args.begin();
      for (uint i = 0;
           i < needed_args.size() && args_at_i != _args.end();
           ++i, ++args_at_i) {
        if (!needed_args[i].second.exact_match(
                ::type(*args_at_i))) {
          throw std::runtime_error(
              "Expected type '" +
              needed_args[i].second.oak_repr() + "' for arg " +
              std::to_string(i) +
              " of fn pointer call, but saw type '" +
              Type(::type(*args_at_i)).oak_repr() + "'");
        }
      }

      ASTNode args("_");
      auto needed_arg = needed_args.begin();
      for (const auto &arg : _args) {
        Type type = ::type(arg);
        int derefs = 0;

        if (!type.cast_match(needed_arg->second)) {
          derefs = -1;
          for (Type t = type.ref();
               !t.exact_match(needed_arg->second);
               t = t.deref()) {
            ++derefs;
          }
        }

        args.children.push_back(ASTNode(
            "_", {arg, ASTNode(std::to_string(derefs))}));
        ++needed_arg;
      }

      assert(!_unmangled_name.empty());
      return ASTNode("@", {ASTNode(_unmangled_name),
                           fn_type.fn_return_type(), args});
      ;
    } else {
      throw std::runtime_error(
          "Cannot call variable with non-function-pointer "
          "type '" +
          local_var_type.oak_repr(_unmangled_name) + "'");
    }
  }

  // End special cases
  //////////////////////////////////////////////////////////////

  return scope_manager.get_fn(_unmangled_name, _args);
}

bool Parser::instantiate(
    TemplateInfo &_what,
    const std::list<std::list<std::string>> &_substitutions,
    std::string &_err_msg) {

  // Replace the instantiation block
  TokenStream replaced_instantiation_block =
      TemplateInfo::replace(_what.instantiate_block,
                            _what.generics, _substitutions);

  if (settings.debug) {
    settings.ostream << "Parsing template block:\n```oak\n";
    uint counter = 0;
    for (const auto &tok : replaced_instantiation_block) {
      settings.ostream << tok.text << ' ';

      counter += tok.text.size() + 1;
      if (counter >= 32) {
        settings.ostream << '\n';
        counter = 0;
      }
    }
    settings.ostream << "\n```\n";
  }

  // Build namespace string
  const std::string prefix =
      build_generic_prefix(_what.name, _substitutions);
  scope_manager.push_prefix(prefix);

  // Run instantiation block
  try {
    parse_global(replaced_instantiation_block);
  } catch (std::runtime_error &e) {
    _err_msg = e.what();
    scope_manager.pop_prefix();
    return false;
  } catch (...) {
    scope_manager.pop_prefix();
    return false;
  }
  scope_manager.pop_prefix();

  return true;
}

void Parser::validate_type(const Type &_t) {
  if (_t.type_ast.children.empty()) {
    const std::string type = _t.type_ast.text;

    if (Type::is_built_in_type(type)) {
      return;
    }

    const auto entry = scope_manager.get(type);

    if (!entry.has_value() ||
        !(std::holds_alternative<StructInfo>(entry.value()) ||
          std::holds_alternative<EnumInfo>(entry.value()))) {
      throw std::runtime_error("Atomic type '" + type +
                               "' does not exist.");
    }

    return;
  }

  const auto t = _t.type_ast.text;
  const auto c = _t.type_ast.children;

  if (t == "[]") {
    validate_type(c.back());
  } else if (t == "^") {
    // Deref
    validate_type(c.back());
  } else if (t == "->") {
    // Fn
    const auto args = c.at(0);
    const auto ret_type = c.at(1);
    for (const auto &arg : args.children) {
      validate_type(arg.children.back());
    }
    validate_type(ret_type);
  }

  else {
    std::cout << __FILE__ << ":" << __LINE__ << "> "
              << "Special case " << _t.type_ast << "\n";
    throw std::runtime_error("UNIMPLEMENTED");
  }
}

void Parser::parse_macro(
    TokenStream &_pos, const uint64_t &_preproc_passes_allowed,
    const std::list<std::string> &_names) {
  debug_print_pos(__FUNCTION__, _pos);

  // Either '=' or '('
  if (_pos.cur().text == "=") {
    _pos.next();

    // Scan until ;
    InlineMacro info;
    while (!_pos.done() && _pos.cur().text != ";") {
      info.contents.push_back(_pos.cur_next());
    }
    _pos.expect({";"});
    for (const auto &name : _names) {
      scope_manager.add(name, info);
    }
  } else if (_pos.cur().text == "(") {
    // Scrape definition
    std::list<Token> contents;
    contents.push_back(Token(_pos.cur(), "let"));
    contents.push_back(Token(_pos.cur(), "main"));

    // Until first "{"
    while (_pos.cur().text != "{") {
      contents.push_back(_pos.cur_next());
      if (_pos.done()) {
        throw std::runtime_error(
            "Functional macro definition '" + _names.front() +
            "' must be followed by body");
      }
    }

    contents.push_back(_pos.cur_next());

    uint count = 1;
    while (count != 0) {
      if (_pos.cur().text == "{") {
        ++count;
      } else if (_pos.cur().text == "}") {
        --count;
      }

      contents.push_back(_pos.cur_next());
    }

    for (const auto &name : _names) {
      // Write to file
      const std::filesystem::path source_path =
          _pos.cur().file.string() + "." +
          name.substr(0, name.size() - 1) + ".macro.oak";
      const std::filesystem::path executable_path =
          source_path.string() + ".out";

      // Skip compilation if possible
      bool do_compile = true;
      if (std::filesystem::exists(executable_path)) {
        const auto src_last_write =
            std::filesystem::last_write_time(_pos.cur().file);
        const auto exe_last_write =
            std::filesystem::last_write_time(executable_path);

        if (src_last_write < exe_last_write) {
          do_compile = false;
        }
      }

      if (do_compile) {
        if (_preproc_passes_allowed == 0) {
          throw std::runtime_error("Cannot compile " +
                                   source_path.string());
        }

        std::ofstream f(source_path);
        if (!f.is_open()) {
          throw std::runtime_error(
              "Failed to write macro source file '" +
              source_path.string() + "'");
        }

        intmax_t cur_line = 1;

        for (const auto &item : contents) {
          if (item.line != cur_line) {
            f << '\n';
            cur_line = item.line;
          } else {
            f << ' ';
          }
          f << item.text;
        }
        f.close();

        // Compile to executable
        std::stringstream macro_compilation_log;
        OakCompiler oc(macro_compilation_log);
        oc.settings.compile_settings().preprocess_pass_limit =
            _preproc_passes_allowed - 1;
        oc.settings.compile_settings().do_syntax_check = false;
        oc.settings.compile_settings().mode = Settings::
            CompileSettings::TRANSLATE_COMPILE_AND_LINK;
        oc.settings.compile_settings().entry_point =
            source_path;
        oc.settings.compile_settings().target = executable_path;
        oc.settings.debug = settings.debug;

        if (oc.settings.debug) {
          oc.settings.ostream << "Compiling macro '" << name
                              << "' from " << source_path
                              << " to " << executable_path
                              << '\n';
        }

        try {
          oc();
        } catch (std::runtime_error &e) {
          throw std::runtime_error(
              "From macro compiler:\n" +
              macro_compilation_log.str() +
              "\nDuring compilation of macro '" + name +
              "':\n" + e.what());
        } catch (...) {
          throw std::runtime_error(
              "From macro compiler:\n" +
              macro_compilation_log.str() +
              "\nUnknown error occurred during "
              "compilation of macro '" +
              name + "'");
        }
      }

      // Save executable
      CompiledMacro c;
      c.executable = executable_path;
      scope_manager.add(name, c);
    }
  } else {
    throw std::runtime_error(
        "Malformed macro definition for " + _names.front() +
        ": Expected '=' or '(', but saw '" + _pos.cur().text +
        "'");
  }
}

void Parser::syntax_check(const std::filesystem::path &_fp,
                          const std::string &_text) const {
  // All detected errors: line, col, message
  std::list<std::tuple<uint64_t, uint64_t, std::string>> errors;

  // Scan for syntax errors here
  uint64_t line = 1, col = 0;
  std::stack<char> enclosure;
  size_t i;

  auto incr = [&]() {
    if (col == 65) {
      errors.push_back({line, col, "Line too long!"});
    }
    ++i, ++col;
  };

  for (i = 0; i < _text.size(); ++i, ++col) {
    // Comments
    if (_text.at(i) == '/' && i + 1 < _text.size() &&
        _text.at(i + 1) == '/') {
      while (i < _text.size() && _text.at(i) != '\n') {
        incr();
      }
      if (_text.at(i) == '\n') {
        ++line, col = 0;
      }
    } else if (_text.at(i) == '/' && i + 1 < _text.size() &&
               _text.at(i + 1) == '*') {
      while (i + 1 < _text.size() &&
             !(_text.at(i) == '*' && _text.at(i + 1) == '/')) {
        if (_text.at(i) == '\n') {
          ++line, col = 0;
        }
        incr();
      }
      incr();
    }

    // Strings
    if (_text.at(i) == '\'') {
      bool skip = false;
      incr();
      while (i < _text.size()) {
        if (skip) {
          skip = false;
        } else if (_text.at(i) == '\\') {
          skip = true;
          incr();
          continue;
        } else if (_text.at(i) == '\'') {
          break;
        } else if (_text.at(i) == '\n') {
          ++line, col = 0;
          break;
        }
        incr();
      }
    } else if (_text.at(i) == '"') {
      bool skip = false;
      incr();
      while (i < _text.size()) {
        if (skip) {
          skip = false;
        } else if (_text.at(i) == '\\') {
          skip = true;
          incr();
          continue;
        } else if (_text.at(i) == '"') {
          break;
        } else if (_text.at(i) == '\n') {
          ++line, col = 0;
          break;
        }
        incr();
      }
    } else if (_text.at(i) == '`') {
      bool skip = false;
      incr();
      while (i < _text.size()) {
        if (skip) {
          skip = false;
        } else if (_text.at(i) == '\\') {
          skip = true;
          incr();
          continue;
        } else if (_text.at(i) == '`') {
          break;
        } else if (_text.at(i) == '\n') {
          ++line, col = 0;
          break;
        }
        incr();
      }
    }

    else {
      // Everything else
      switch (_text.at(i)) {
      case '\n':
        ++line, col = 0;
        break;
      case '[':
      case '(':
      case '{':
        enclosure.push(_text.at(i));
        break;
      case ']':
        if (enclosure.empty()) {
          errors.push_back({line, col, "Too many ']'"});
        } else if (enclosure.top() != '[') {
          errors.push_back({line, col,
                            std::string("Tried to end '") +
                                enclosure.top() +
                                "' with ']'"});
        } else {
          enclosure.pop();
        }
        break;
      case ')':
        if (enclosure.empty()) {
          errors.push_back({line, col, "Too many ')'"});
        } else if (enclosure.top() != '(') {
          errors.push_back({line, col,
                            std::string("Tried to end '") +
                                enclosure.top() +
                                "' with ')'"});
        } else {
          enclosure.pop();
        }
        break;
      case '}':
        if (enclosure.empty()) {
          errors.push_back({line, col, "Too many '}'"});
        } else if (enclosure.top() != '{') {
          errors.push_back({line, col,
                            std::string("Tried to end '") +
                                enclosure.top() +
                                "' with '}'"});
        } else {
          enclosure.pop();
        }
        break;
      }

      if (col == 65) {
        errors.push_back({line, col, "Line too long!"});
      }
    }
  }

  // If errors were found, throw them
  if (!errors.empty()) {
    for (const auto &p : errors) {
      settings.ostream << _fp.string() << ":" << std::get<0>(p)
                       << "." << std::get<1>(p) << "> '"
                       << std::get<2>(p) << "'\n";
    }

    throw std::runtime_error(std::to_string(errors.size()) +
                             " syntax error(s) occurred.");
  }
}

void Parser::load_dialect_file(
    const std::filesystem::path &_path) {

  // Parse that file
  OakCompiler c(settings.ostream);
  Settings::CompileSettings &csettings =
      c.settings.compile_settings();
  csettings = settings.compile_settings();
  csettings.mode = Settings::CompileSettings::NOTHING;
  csettings.entry_point = _path;
  c();

  // pragma!("export_dialect", "one_rule_name");
  if (csettings.pragmas.at(_path).contains("export_dialect")) {
    // for (const auto &rule : c.rules.rules) {
    //   rules.register_rule(rule.first, rule.second);
    // }
    // for (const auto &bundle : c.rules.bundles) {
    //   rules.register_bundle(bundle.first, bundle.second);
    // }
    std::cerr << __FILE__ << ":" << __LINE__
              << "> Unimplemented\n"
              << std::flush;

    settings.dialect =
        csettings.pragmas.at(_path).at("export_dialect");
  } else {
    throw std::runtime_error(
        "Dialect file '" + _path.string() +
        "' does contain `pragma!(\"export_dialect\", "
        "\"...\");`");
  }
}

std::filesystem::path
Parser::resolve_path(const std::string &_requested,
                     const std::filesystem::path &_cur_file) {
  const auto local = _cur_file.parent_path() / _requested;
  const auto global =
      settings.compile_settings().include_path / _requested;
  const bool global_exists = std::filesystem::exists(global);

  if (std::filesystem::exists(local)) {
    if (global_exists &&
        std::filesystem::canonical(global) !=
            std::filesystem::canonical(local)) {
      settings.warn(_requested, 0, 0,
                    "Choosing local file " + _requested +
                        " over package file of same name");
    }
    return std::filesystem::canonical(local);
  } else if (global_exists) {
    return std::filesystem::canonical(global);
  } else {
    throw std::runtime_error("Failed to resolve file '" +
                             _requested + "'");
  }
}

void Parser::do_file(const std::string &_path,
                     const std::filesystem::path &_cur_file) {

  const auto path = resolve_path(_path, _cur_file);

  Settings::CompileSettings &csettings =
      settings.compile_settings();

  if (csettings.visited.contains(path)) {
    if (settings.debug) {
      settings.ostream << "Ignoring repeat inclusion " << path
                       << '\n';
    }
    return;
  }

  if (settings.debug) {
    settings.ostream << "Visiting file " << path << '\n';
  }

  const auto path_write_time =
      std::filesystem::last_write_time(path);
  if (path_write_time > csettings.most_recent_mod_time) {
    csettings.most_recent_mod_time = path_write_time;
  }
  csettings.visited.insert(path);

  // Load and lex
  if (!std::filesystem::exists(path)) {
    throw std::runtime_error("File " + path.string() +
                             " does not exist.");
  } else if (!std::filesystem::is_regular_file(path)) {
    throw std::runtime_error(
        "File " + path.string() +
        " exists, but is not a regular file.");
  }

  std::string text;
  std::ifstream source(path);
  if (!source.is_open()) {
    throw std::runtime_error("Failed to open file " +
                             path.string());
  }

  text.assign(std::istreambuf_iterator<char>(source),
              std::istreambuf_iterator<char>());
  source.close();

  uint64_t line = 1, col = 0;
  TokenStream token_stream({});

  // Lex
  try {
    token_stream = lex(text, path, line, col, true);
    if (settings.debug) {
      std::cout << "Lexed token stream (after fixing math):\n";
      for (const auto &tok : token_stream) {
        std::cout << tok.text << ' ';
      }
      std::cout << "\n";
    }
  } catch (std::runtime_error &e) {
    // If requested, dump
    if (csettings.dump_file.has_value()) {
      dump(*csettings.dump_file.value(), token_stream);
    }

    throw std::runtime_error("Error occurred while lexing " +
                             path.string() + ":\n" + e.what());
  } catch (...) {
    // If requested, dump
    if (csettings.dump_file.has_value()) {
      dump(*csettings.dump_file.value(), token_stream);
    }

    throw std::runtime_error(
        "An unknown error occurred while lexing " +
        path.string() + "");
  }

  // If requested, syntax check
  if (csettings.do_syntax_check) {
    syntax_check(path, text);
  }

  // Do actual parsing here
  const auto starting_pos = token_stream.tell();
  try {
    parse_global(token_stream);
  } catch (...) {
    print_region(token_stream, settings.ostream, 5);
    throw;
  }

  token_stream.seek(starting_pos);

  // If requested, dump
  if (csettings.dump_file.has_value()) {
    dump(*csettings.dump_file.value(), token_stream);
  }

  if (settings.debug) {
    settings.ostream << "Exiting file " << path << '\n';
  }
}

bool Parser::replace_macro(TokenStream &_pos) {

  debug_print_pos(__FUNCTION__, _pos);

  const auto name_tok = _pos.cur();
  if (name_tok.text.find("!") == std::string::npos) {
    return false;
  }

  const std::string name =
      _pos.cur().text.substr(0, _pos.cur().text.find('!') + 1);
  const std::string nonexistence_replacement =
      _pos.cur().text.substr(_pos.cur().text.find('!') + 1);

  if (name == "LINE!") {
    _pos.cur_mut().text =
        std::to_string(_pos.cur().line) + "u64";
    return true;
  } else if (name == "COL!") {
    _pos.cur_mut().text =
        std::to_string(_pos.cur().col) + "u64";
    return true;
  } else if (name == "FILE!") {
    _pos.cur_mut().text = '"' + _pos.cur().file.string() + '"';
    return true;
  } else if (name == "oak_VERSION!") {
    _pos.cur_mut().text = '"' + acorn_version + '"';
    return true;
  } else if (name == "SYSTEM!") {
#if (defined(WIN32) || defined(WINNT))
    _pos.cur_mut().text = "\"WINDOWS\"";
#elif (defined(unix) || defined(__unix__))
    _pos.cur_mut().text = "\"UNIX\"";
#elif (defined(__APPLE__) || defined(__MACH__))
    _pos.cur_mut().text = "\"OSX\"";
#else
    _pos.cur_mut().text = "\"OTHER\"";
#endif
    return true;
  }

  // Note: Still pointing to name
  if (reserved_macro_names.contains(name)) {
    if (name == "compile_time_error!") {
      std::stringstream msg_strm;
      msg_strm << _pos.cur().file.string() << ":"
               << _pos.cur().line << "." << _pos.cur().col
               << "> Compile-time error:\n";
      const auto args = get_macro_args(_pos);
      for (const auto &arg : args) {
        for (const auto &tok : arg) {
          msg_strm << tok.text + " ";
        }
        msg_strm << " ";
      }
      msg_strm << '\n';

      settings.ostream << msg_strm.str();
      throw std::runtime_error(msg_strm.str());
    } else if (name == "compile_time_warning!") {
      std::stringstream msg_strm;
      msg_strm << " Compile-time warning:\n";
      const auto args = get_macro_args(_pos);
      for (const auto &arg : args) {
        for (const auto &tok : arg) {
          msg_strm << tok.text + " ";
        }
        msg_strm << " ";
      }
      msg_strm << '\n';
      settings.warn(_pos.cur().file, _pos.cur().line,
                    _pos.cur().col, msg_strm.str());
    } else if (name == "compile_time_print!") {
      settings.ostream
          << _pos.cur().file.string() << ":" << _pos.cur().line
          << "." << _pos.cur().col << "> Compile-time print:\n";
      const auto args = get_macro_args(_pos);
      for (const auto &arg : args) {
        for (const auto &tok : arg) {
          settings.ostream << tok.text + " ";
        }
        settings.ostream << " ";
      }
      settings.ostream << '\n';
    } else if (name == "alias!") {
      // In Oak: alias!(to, from);
      // In C++: using to = from;
      const auto args = get_macro_args(_pos);
      if (args.size() != 2) {
        throw std::runtime_error(
            "'alias!' takes two arguments: to and from");
      }
      scope_manager.alias(concat(args.front()),
                          concat(args.back()));
    } else if (name == "erase!") {
      const auto args = get_macro_args(_pos);
      for (const auto &entry : args) {
        scope_manager.erase(concat(entry));
      }
    } else if (name == "namespace_use!") {
      // In Oak: namespace::use!("std");
      // In C++: using namespace std;

      const auto args = get_macro_args(_pos);
      if (args.size() != 1) {
        throw std::runtime_error(
            "'namespace::use!' takes one "
            "string argument: The prefix to "
            "remove");
      }
      scope_manager.remove_prefix(concat(args.front()));
    } else if (name == "include!") {
      auto raw_args = get_macro_args(_pos);

      std::list<Token> args;
      for (auto it = raw_args.begin(); it != raw_args.end();
           ++it) {
        TokenStream cur_arg(*it);
        Token to_add = cur_arg.cur();
        for (cur_arg.next(); !cur_arg.done(); cur_arg.next()) {
          to_add.text += ' ';
          to_add.text += cur_arg.cur().text;
        }
        to_add.text = strip_string_literal(to_add.text);
        args.push_back(to_add);
      }

      for (const auto &f : args) {
        do_file(f.text, f.file);
      }
    } else if (name == "link!") {
      auto raw_args = get_macro_args(_pos);
      std::list<Token> args;
      for (auto it = raw_args.begin(); it != raw_args.end();
           ++it) {
        TokenStream cur_arg(*it);
        Token to_add = cur_arg.cur();
        for (cur_arg.next(); !cur_arg.done(); cur_arg.next()) {
          to_add.text += ' ';
          to_add.text += cur_arg.cur().text;
        }
        args.push_back(to_add);
      }

      for (auto it = args.begin(); it != args.end(); ++it) {
        it->text = strip_string_literal(it->text);
      }

      for (const auto &f : args) {
        settings.compile_settings().objects.push_back(
            resolve_path(f.text, f.file));
      }
    } else if (name == "flag!") {
      auto raw_args = get_macro_args(_pos);
      std::list<Token> args;
      for (auto it = raw_args.begin(); it != raw_args.end();
           ++it) {
        TokenStream cur_arg(*it);
        Token to_add = cur_arg.cur();
        for (cur_arg.next(); !cur_arg.done(); cur_arg.next()) {
          to_add.text += ' ';
          to_add.text += cur_arg.cur().text;
        }
        args.push_back(to_add);
      }

      for (auto it = args.begin(); it != args.end(); ++it) {
        it->text = strip_string_literal(it->text);
      }

      for (const auto &f : args) {
        settings.compile_settings().link_flags.push_back(
            f.text);
      }
    } else if (name == "pragma!") {
      auto raw_args = get_macro_args(_pos);
      std::list<Token> args;
      for (auto it = raw_args.begin(); it != raw_args.end();
           ++it) {
        TokenStream cur_arg(*it);
        Token to_add = cur_arg.cur();
        for (cur_arg.next(); !cur_arg.done(); cur_arg.next()) {
          to_add.text += ' ';
          to_add.text += cur_arg.cur().text;
        }
        args.push_back(to_add);
      }

      for (auto it = args.begin(); it != args.end(); ++it) {
        it->text = strip_string_literal(it->text);
      }

      if (args.size() == 1) {
        args.push_back(Token(args.front(), ""));
      }

      settings.compile_settings()
          .pragmas[_pos.cur().file][args.front().text] =
          std::next(args.begin())->text;
    } else if (name == "rule_new!") {
      auto raw_args = get_macro_args(_pos);
      std::list<Token> args;
      for (auto it = raw_args.begin(); it != raw_args.end();
           ++it) {
        TokenStream cur_arg(*it);

        Token to_add = cur_arg.cur();
        for (cur_arg.next(); !cur_arg.done(); cur_arg.next()) {
          to_add.text += ' ';
          to_add.text += cur_arg.cur().text;
        }
        args.push_back(to_add);
      }

      for (auto it = args.begin(); it != args.end(); ++it) {
        it->text = strip_string_literal(it->text);
      }

      if (args.size() < 3) {
        throw std::runtime_error(
            "Malformed rule::new! call: Arguments must "
            "be "
            "rule_name, input_rule, output_rule, "
            "[engine_name], [prerequisites...]");
      }

      // Name, input, output (using sapling engine)
      std::string name = args.front();
      std::string engine = "sapling";
      std::list<std::string> prereqs;
      if (args.size() == 4) {
        // Name, input, output, engine
        engine = *std::next(args.begin(), 3);
      } else if (args.size() > 4) {
        // Name, input, output, engine, prerequisites
        engine = *std::next(args.begin(), 3);
        for (auto it = std::next(args.begin(), 4);
             it != args.end(); ++it) {
          prereqs.push_back(_pos.cur());
        }
      }

      std::cerr << __FILE__ << ":" << __LINE__
                << "> Unimplemented\n"
                << std::flush;
    } else if (name == "rule_use!") {
      auto raw_args = get_macro_args(_pos);
      std::list<Token> args;
      for (auto it = raw_args.begin(); it != raw_args.end();
           ++it) {
        TokenStream cur_arg(*it);

        Token to_add = cur_arg.cur();
        for (cur_arg.next(); !cur_arg.done(); cur_arg.next()) {
          to_add.text += ' ';
          to_add.text += cur_arg.cur().text;
        }
        args.push_back(to_add);
      }

      std::cerr << __FILE__ << ":" << __LINE__
                << "> Unimplemented\n"
                << std::flush;
    } else if (name == "rule_remove!") {
      auto raw_args = get_macro_args(_pos);
      std::list<Token> args;
      for (auto it = raw_args.begin(); it != raw_args.end();
           ++it) {
        TokenStream cur_arg(*it);

        Token to_add = cur_arg.cur();
        for (cur_arg.next(); !cur_arg.done(); cur_arg.next()) {
          to_add.text += ' ';
          to_add.text += cur_arg.cur().text;
        }
        args.push_back(to_add);
      }

      // for (const auto &_ : args) {
      std::cerr << __FILE__ << ":" << __LINE__
                << "> Unimplemented\n"
                << std::flush;
      // }
    } else if (name == "rule_bundle!") {
      auto raw_args = get_macro_args(_pos);
      std::list<Token> args;
      for (auto it = raw_args.begin(); it != raw_args.end();
           ++it) {
        TokenStream cur_arg(*it);

        Token to_add = cur_arg.cur();
        for (cur_arg.next(); !cur_arg.done(); cur_arg.next()) {
          to_add.text += ' ';
          to_add.text += cur_arg.cur().text;
        }
        args.push_back(to_add);
      }

      std::list<std::string> entails;
      for (auto it = std::next(args.begin()); it != args.end();
           ++it) {
        entails.push_back(strip_string_literal(it->text));
      }

      std::cerr << __FILE__ << ":" << __LINE__
                << "> Unimplemented\n"
                << std::flush;
    } else if (name == "unstr!") {
      const auto first_of_range = _pos.tell();
      Token to_add = _pos.cur(); // name
      auto raw_args = get_macro_args(_pos);
      const auto first_after_range = _pos.tell();

      to_add.text.clear();
      for (auto it = raw_args.begin(); it != raw_args.end();
           ++it) {
        for (auto inner_it = it->begin(); inner_it != it->end();
             ++inner_it) {
          if (!to_add.text.empty()) {
            to_add.text += ' ';
          }
          to_add.text += inner_it->text;
        }
      }

      to_add.text = strip_string_literal(to_add.text);

      uint64_t dummy_line = to_add.line, dummy_col = to_add.col;
      TokenStream to_insert =
          lex(to_add.text, to_add.file, dummy_line, dummy_col);

      _pos.rangef(first_of_range, first_after_range,
                  {to_insert});
    } else if (name == "str!") {
      Token to_add(_pos.cur());

      const auto first_of_range = _pos.tell();
      auto raw_args = get_macro_args(_pos);
      const auto first_after_range = _pos.tell();
      to_add.text.clear();

      for (auto it = raw_args.begin(); it != raw_args.end();
           ++it) {
        for (auto inner_it = it->begin(); inner_it != it->end();
             ++inner_it) {
          if (!to_add.text.empty()) {
            to_add.text += ' ';
          }
          to_add.text += inner_it->text;
        }
      }

      // Ensure exactly one set of enclosing quotes
      to_add.text = make_string_literal(
          strip_string_literal(to_add.text));

      _pos.rangef(first_of_range, first_after_range, {to_add});
      _pos.seek(first_of_range);
    } else if (name == "compile_time_system!") {
      settings.ostream
          << _pos.cur().file.string() << ":" << _pos.cur().line
          << "." << _pos.cur().col
          << ">\ncompile_time::system! asks to run `";
      auto raw_args = get_macro_args(_pos);
      std::list<Token> args;
      for (auto it = raw_args.begin(); it != raw_args.end();
           ++it) {
        TokenStream cur_arg(*it);

        Token to_add = cur_arg.cur();
        for (cur_arg.next(); !cur_arg.done(); cur_arg.next()) {
          to_add.text += ' ';
          to_add.text += cur_arg.cur().text;
        }
        args.push_back(to_add);
      }

      for (auto it = args.begin(); it != args.end(); ++it) {
        it->text = strip_string_literal(it->text);
      }

      std::string cmd;
      for (const auto &arg : args) {
        if (!cmd.empty()) {
          cmd.push_back(' ');
        }
        cmd += arg.text;
      }

      settings.ostream << cmd << "` at "
                       << _pos.cur().file.parent_path() << "\n"
                       << std::flush;

      if (!settings.compile_settings().no_confirm) {
        settings.ostream << "Allow? [N/y/a] ";
        char choice = std::cin.get();

        switch (choice) {
        default:
          throw std::runtime_error("Abort!");
        case 'a':
        case 'A':
          settings.ostream << "Not asking again!\n";
          settings.compile_settings().no_confirm = true;
        case 'y':
        case 'Y':
          break;
        }
      } else {
        settings.ostream
            << "(no_confirm is enabled, so running "
               "without asking)\n";
      }

      const auto old_cwd = std::filesystem::current_path();
      std::filesystem::current_path(
          _pos.cur().file.parent_path());

      auto result = system(cmd.c_str());

      std::filesystem::current_path(old_cwd);

      if (result != 0) {
        throw std::runtime_error(
            "System call '" + cmd +
            "' exited with nonzero exit code " +
            std::to_string(result));
      }
    } else {
      throw std::runtime_error(
          "Unhandled special-case macro '" + name + "'");
    }
    return true;
  }

  const auto res = scope_manager.get(name);
  if (!res.has_value()) {
    if (!nonexistence_replacement.empty()) {
      _pos.cur_mut().text = nonexistence_replacement;
    } else {
      throw std::runtime_error("Macro '" + name +
                               "' has no definition");
    }
  } else if (std::holds_alternative<InlineMacro>(res.value())) {
    // Inline
    auto first_of_range = _pos.tell();
    _pos.rangef(first_of_range, first_of_range + 1,
                {std::get<InlineMacro>(res.value()).contents});
    _pos.seek(first_of_range);
  } else if (_pos.peek().text == "(") {
    // Functional
    const auto first_of_range = _pos.tell();
    _pos.next();
    auto args = get_macro_args(_pos);
    const auto first_after_range = _pos.tell();

    const auto exe =
        std::get<CompiledMacro>(res.value()).executable;

    if (!std::filesystem::exists(exe)) {
      throw std::runtime_error("Compiled macro " +
                               exe.string() +
                               " does not exist!");
    }

    // Prepare call
    std::string command = exe;
    for (const auto &arg : args) {
      std::string arg_text;
      for (const auto &tok : arg) {
        if (!arg_text.empty()) {
          arg_text.push_back(' ');
        }
        arg_text += tok;
      }
      command += " " + make_string_literal(arg_text);
    }

    if (settings.debug) {
      settings.ostream << "Running macro call '" << command
                       << "'\n";
    }

    // Run call and get replacement
    const auto replacement = get_cmd_output(command);

    if (settings.debug) {
      settings.ostream << "Macro returned text:\n```oak\n"
                       << replacement << "\n```\n";
    }

    // Lex replacement
    uint64_t junk_line = 0, junk_col = 0;
    auto lexed_replacement =
        lex(replacement, name_tok.file, junk_line, junk_col);

    // Do replacement
    _pos.rangef(first_of_range, first_after_range,
                {lexed_replacement});
    _pos.seek(first_of_range);
  } else {
    // Error
    throw std::runtime_error(
        "Compiled macro '" + name +
        "' must be invoked as a function call.");
  }
  return true;
}

FnInfo Parser::get_default_constructor(const StructInfo &_what,
                                       const Token &_where) {
  assert(!_what.name.empty());
  FnInfo out;
  out.name = "New";
  out.t = ASTNode(
      "->",
      {ASTNode(
           "_",
           {ASTNode("arg",
                    {ASTNode("self"),
                     ASTNode("^", {ASTNode(_what.name)})})}),
       ASTNode("void")});
  out.tags["autogen"] = "true";
  out.n = ASTNode("statement", {});
  for (const auto &member : _what.member_order) {
    out.n.children.push_back(ASTNode(
        "statement",
        {get_function_call_node(
            "New", {ASTNode("object",
                            {_what.members.at(member).ref(),
                             ASTNode("self." + member)})})}));
  }
  return out;
}

FnInfo Parser::get_default_destructor(const StructInfo &_what,
                                      const Token &_where) {
  assert(!_what.name.empty());
  FnInfo out;
  out.name = "Del";
  out.t = ASTNode(
      "->",
      {ASTNode(
           "_",
           {ASTNode("arg",
                    {ASTNode("self"),
                     ASTNode("^", {ASTNode(_what.name)})})}),
       ASTNode("void")});
  out.tags["autogen"] = "true";
  out.n = ASTNode("statement", {});
  for (auto it = _what.member_order.rbegin();
       it != _what.member_order.rend(); ++it) {
    out.n.children.push_back(ASTNode(
        "statement",
        {get_function_call_node(
            "Del",
            {ASTNode("object", {_what.members.at(*it).ref(),
                                ASTNode("self." + *it)})})}));
  }
  return out;
}

FnInfo Parser::get_default_constructor(const EnumInfo &_what,
                                       const Token &_where) {
  const std::string op = _what.option_order.front();
  assert(!_what.name.empty());
  FnInfo out;
  out.name = "New";
  out.t = ASTNode(
      "->",
      {ASTNode(
           "_",
           {ASTNode("arg",
                    {ASTNode("self"),
                     ASTNode("^", {ASTNode(_what.name)})})}),
       ASTNode("void")});
  out.tags["autogen"] = "true";
  out.n = ASTNode(
      "statement",
      {ASTNode("statement",
               {get_function_call_node(
                   "New", {ASTNode("object",
                                   {_what.options.at(op).ref(),
                                    ASTNode("self->__data." +
                                            op)})})})});
  return out;
}

FnInfo Parser::get_default_destructor(const EnumInfo &_what,
                                      const Token &_where) {
  assert(!_what.name.empty());
  FnInfo out;
  out.name = "Del";
  out.t = ASTNode(
      "->",
      {ASTNode(
           "_",
           {ASTNode("arg",
                    {ASTNode("self"),
                     ASTNode("^", {ASTNode(_what.name)})})}),
       ASTNode("void")});

  ASTNode branches("_");
  for (const auto &option : _what.option_order) {
    assert(!option.empty());
    const auto option_type = _what.options.at(option);
    const auto delete_call = get_function_call_node(
        "Del", {ASTNode("object",
                        {option_type.ref(), ASTNode("data")})});
    branches.children.push_back(
        ASTNode("case", {ASTNode(option), ASTNode("data"),
                         option_type.ref(), delete_call}));
  }

  out.n = ASTNode(
      "statement",
      {ASTNode(
          "match",
          {ASTNode("object", {Type(ASTNode(_what.name)).ref(),
                              ASTNode("self")}),
           branches, ASTNode(_what.name), ASTNode("true")})});

  return out;
}

std::list<FnInfo> Parser::get_wrappers(const EnumInfo &_what,
                                       const Token &_where) {
  assert(!_what.name.empty());
  std::list<FnInfo> out;
  for (const auto &p : _what.options) {
    const auto wrapper_name = "wrap_" + p.first;
    FnInfo to_add;
    to_add.name = wrapper_name;

    to_add.tags["file"] = _where.file;
    to_add.tags["line"] = std::to_string(_where.line);
    to_add.tags["col"] = std::to_string(_where.col);

    // Construct wrapper type
    to_add.t = Type(ASTNode(
        "->",
        {
            ASTNode(
                "_",
                {
                    ASTNode("arg",
                            {
                                ASTNode("self"),
                                ASTNode("^",
                                        {
                                            ASTNode(_what.name),
                                        }),
                            }),
                    ASTNode("arg",
                            {
                                ASTNode("__data"),
                                p.second,
                            }),
                }),
            ASTNode("void"),
        }));

    // Node
    ASTNode child(
        "raw_c_format",
        {ASTNode("{ self->__info = " + _what.name + "_OPT_" +
                 p.first + "; self->__data." + p.first +
                 " = __data; }"),
         ASTNode("void"), ASTNode("_", {})});
    to_add.n = ASTNode("statement", {child});

    // Insert fn
    out.push_back(to_add);
  }
  return out;
}
