name: GitHub Actions CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y clang libboost-all-dev git
        sudo apt install -y libsdl2-dev colorized-logs
        make install packages so
    - name: Run tests
      run: |
        make test
